name: Build & Publish SMARTi EMS

on:
  push:
    branches: [ main, master ]
    paths:
      - 'smarti-ems/**'
      - '.github/workflows/build.yaml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'smarti-ems/**'
  workflow_dispatch: {}
  # Optional: build on tags and use that tag as image version
  # tags:
  #   - 'v*'

jobs:
  build:
    name: Build & Push (matrix)
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: amd64
            platform: linux/amd64
          - arch: aarch64
            platform: linux/arm64
          - arch: armv7
            platform: linux/arm/v7

    env:
      IMAGE_OWNER: prosono   # <-- set your GitHub org/user (lowercase)
      ADDON_DIR: smarti-ems

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Read add-on version
        id: meta
        run: |
          VERSION="$(grep -E '^version:' ${ADDON_DIR}/config.yaml | head -n1 | awk '{print $2}' | tr -d '"' )"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "Using add-on version: ${VERSION}"

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.ADDON_DIR }}
          file: ${{ env.ADDON_DIR }}/Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          build-args: |
            arch=${{ matrix.arch }}
          tags: |
            ghcr.io/${{ env.IMAGE_OWNER }}/${{ matrix.arch }}-addon-smarti_ems:${{ steps.meta.outputs.version }}
            ghcr.io/${{ env.IMAGE_OWNER }}/${{ matrix.arch }}-addon-smarti_ems:latest
